# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-13 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_address_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.CharField(max_length=254),
        ),
    ]
